"""Regenerate the _vault/board/*.md files as read-only mirrors of dashboard_tasks.

Since 2026-07-06 the canonical task list is the dashboard_tasks table (CWDB HQ
to-do tab). The Obsidian board files remain so vault links keep working, but
they are GENERATED: every dashboard mutation rewrites them. Mapping:

    in-flight.md  <- status open/deferred (grouped by owner)
    shipped.md    <- status done (newest first, capped)
    killed.md     <- status declined
    directives.md <- pointer stub (new asks go straight into the dashboard)

Deterministic template, no judgment needed, so the Python app owns this;
memory/agent updates (which DO need judgment) go through /dashboard-sync.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from . import config, db

_HEADER = (
    "%% GENERATED by CWDB HQ ({today}) - do not edit by hand.\n"
    "%% Canonical task list: Supabase dashboard_tasks (dashboard to-do tab).\n"
    "%% Edit via the dashboard; this file is rewritten on every change. %%\n\n"
)

_OWNER_LABELS = {
    "jim": "Jim (real life)",
    "project": "Project work (Claude / agents)",
    "others": "Other people (Ben/John, legal, CPA)",
}


def _item_md(t: dict[str, Any]) -> str:
    ref = t.get("source_ref") or f"task-{t['task_id']}"
    lines = [f"- [{ref}] {t['title']}"]
    if t.get("detail"):
        lines.append(f"  - Detail: {t['detail']}")
    lines.append(f"  - Owner: {t.get('owner_detail') or t['owner_group']} · Priority: {t['priority']}"
                 + (f" · Effort: {t['effort']}" if t.get("effort") else ""))
    if t["status"] == "deferred" and t.get("deferred_until"):
        lines.append(f"  - Deferred until: {t['deferred_until']}")
    if t.get("notes"):
        lines.append(f"  - Notes: {t['notes']}")
    if t.get("completed_at"):
        lines.append(f"  - Closed: {str(t['completed_at'])[:10]}")
    return "\n".join(lines)


def regenerate() -> None:
    if config.is_read_only():
        return
    tasks = db.select("dashboard_tasks", "select=*&order=priority.asc,task_id.asc")
    today = date.today().isoformat()
    header = _HEADER.format(today=today)

    open_tasks = [t for t in tasks if t["status"] in ("open", "deferred")]
    done = sorted((t for t in tasks if t["status"] == "done"),
                  key=lambda t: str(t.get("completed_at") or ""), reverse=True)
    declined = [t for t in tasks if t["status"] == "declined"]

    parts = [header, "# In-flight (mirror of CWDB HQ open tasks)\n"]
    for group in ("jim", "project", "others"):
        rows = [t for t in open_tasks if t["owner_group"] == group]
        if not rows:
            continue
        parts.append(f"\n## {_OWNER_LABELS[group]}\n")
        parts.extend(_item_md(t) + "\n" for t in rows)
    (config.BOARD_DIR / "in-flight.md").write_text("".join(parts), encoding="utf-8")

    parts = [header, "# Shipped\n\n"]
    parts.extend(_item_md(t) + "\n" for t in done[:50])
    (config.BOARD_DIR / "shipped.md").write_text("".join(parts), encoding="utf-8")

    parts = [header, "# Killed\n\n"]
    parts.extend(_item_md(t) + "\n" for t in declined)
    (config.BOARD_DIR / "killed.md").write_text("".join(parts), encoding="utf-8")

    (config.BOARD_DIR / "directives.md").write_text(
        header
        + "# Directives\n\n"
        + "New asks go straight into the CWDB HQ dashboard (to-do tab, Add task),\n"
        + "which is the canonical tracker. See [[in-flight]] for the open mirror.\n",
        encoding="utf-8",
    )
