(function(){if(window.__cwdbR3Loaded)return;window.__cwdbR3Loaded=true;function r(f){if(document.readyState!='loading')f();else document.addEventListener('DOMContentLoaded',f)}function nuke(re){var out=[],w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),n;while(n=w.nextNode())if(re.test(n.textContent))out.push(n);out.forEach(function(n){var el=n.parentElement;if(el&&(el.tagName=='SCRIPT'||el.tagName=='STYLE'))return;n.textContent=n.textContent.replace(re,'48 hours')})}var re24=/24 hours/gi;r(function(){try{
// Block 5b: remove devnote leak at body top
var bkids=Array.from(document.body.childNodes);bkids.forEach(function(n){if(n.nodeType===3&&/\/operations\//.test(n.textContent))n.remove();else if(n.nodeType===1){var t=(n.textContent||'').trim();if(t.startsWith('/operations/')&&t.length<300)n.remove()}});
// Block 1a: footer /deck-builders-* → /service-area/*
document.querySelectorAll('a[href^="/deck-builders-"]').forEach(function(a){a.setAttribute('href',a.getAttribute('href').replace('/deck-builders-','/service-area/'))});
// Block 1c: Footer NAP (idempotent).
var fw=document.querySelector('.footer-wrap');if(fw&&fw.getAttribute('data-cwdb-nap')!=='applied'){var cols=fw.querySelectorAll('[class*="footer-col"],.footer-column');var contact=null;cols.forEach(function(c){if(/Contact/i.test(c.textContent))contact=c});if(contact){var addr=document.createElement('p');addr.className='footer-link';var a1=document.createTextNode('906 N 16th Ave');var br=document.createElement('br');var a2=document.createTextNode('Wausau, WI 54401');addr.appendChild(a1);addr.appendChild(br);addr.appendChild(a2);var em=document.createElement('a');em.className='footer-link';em.setAttribute('href','mailto:info@cwdeckbuilders.com');em.textContent='info@cwdeckbuilders.com';var h=contact.querySelector('h3,h4,h5');if(h&&h.nextSibling)contact.insertBefore(addr,h.nextSibling);else contact.appendChild(addr);var telA=contact.querySelector('a[href^="tel:"]');if(telA&&telA.parentElement)telA.parentElement.insertBefore(em,telA.nextSibling);else contact.appendChild(em)}fw.setAttribute('data-cwdb-nap','applied')}
// Block 2: Resources dropdown href rewrites
var RES={'Cost Calculator':'/cost-calculator','Deck Permits Guide':'/blog/deck-permits-wausau','Blog':'/blog','FAQ':'/faq'};document.querySelectorAll('a[href="#"]').forEach(function(a){var t=a.textContent.trim();if(RES[t])a.setAttribute('href',RES[t])});
// Block 3/4/8: form placeholders, inputmode, label for wiring
var PH={'wizard-zip':'54401','wizard-phone':'(715) 555-0100','wizard-address':'123 Main St, Wausau','wizard-notes':'e.g. 12x16 composite with railing, off the back of the house','hero-zip':'54401','hero-phone':'(715) 555-0123'};Object.keys(PH).forEach(function(id){var el=document.getElementById(id);if(el)el.setAttribute('placeholder',PH[id])});document.querySelectorAll('input[placeholder="Example text"],textarea[placeholder="Example text"],select[placeholder="Example text"]').forEach(function(el){if(el.type==='hidden'){el.removeAttribute('placeholder');return}});
// Wire labels + ids + inputmode + aria
function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}document.querySelectorAll('form label').forEach(function(l){if(l.getAttribute('for'))return;var fg=l.parentElement;if(!fg)return;var inp=fg.querySelector('input:not([type=hidden]):not([type=checkbox]),select,textarea');if(!inp)return;var id=inp.id;if(!id){id='fld-'+slug(l.textContent.trim());inp.id=id}l.setAttribute('for',id);if(!inp.getAttribute('aria-label')){var lt=l.textContent.trim().replace(/\*$/,'').trim();inp.setAttribute('aria-label',lt)}});var zip=document.getElementById('wizard-zip');if(zip){zip.setAttribute('inputmode','numeric')}var ph=document.getElementById('wizard-phone');if(ph){ph.setAttribute('inputmode','tel')}var hz=document.getElementById('hero-zip');if(hz)hz.setAttribute('inputmode','numeric');var hp=document.getElementById('hero-phone');if(hp)hp.setAttribute('inputmode','tel');
// Select placeholders
var sp={'wizard-project-type':'Select project type','wizard-budget':'Select budget range','wizard-timeline':'Select timeline','wizard-owns-property':'Select one'};Object.keys(sp).forEach(function(id){var s=document.getElementById(id);if(!s)return;var o=s.options[0];if(o&&(o.text==='Select one'||o.text==='Example text')){o.text=sp[id]}});
// Blocks 3/4/5/6/7: Replace "24 hours" → "48 hours" in visible text only
nuke(re24);
// Block 5b: Inject LocalBusiness JSON-LD on homepage only
if(location.pathname==='/'||location.pathname===''||location.pathname==='/index.html'){if(!document.querySelector('script[data-cwdb-lb]')){var jl=document.createElement('script');jl.type='application/ld+json';jl.setAttribute('data-cwdb-lb','1');jl.textContent=JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness","@id":"https://cwdeckbuilders.com/#business","name":"Central Wisconsin Deck Builders","alternateName":"CWDB","url":"https://cwdeckbuilders.com","telephone":"+1-715-544-7941","email":"info@cwdeckbuilders.com","priceRange":"$$","address":{"@type":"PostalAddress","streetAddress":"906 N 16th Ave","addressLocality":"Wausau","addressRegion":"WI","postalCode":"54401","addressCountry":"US"},"geo":{"@type":"GeoCoordinates","latitude":44.9591,"longitude":-89.6301},"areaServed":[{"@type":"City","name":"Wausau"},{"@type":"City","name":"Schofield"},{"@type":"City","name":"Weston"},{"@type":"City","name":"Mosinee"},{"@type":"City","name":"Merrill"}],"serviceType":"Deck Building","openingHoursSpecification":[{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday"],"opens":"07:00","closes":"18:00"}]});document.head.appendChild(jl)}}
// Block 7: FAQPage JSON-LD on /faq
if(/^\/faq\/?$/.test(location.pathname)){if(!document.querySelector('script[data-cwdb-faq]')){var items=[];document.querySelectorAll('.w-dyn-item,.faq-item,[class*="faq-item"]').forEach(function(it){var q=it.querySelector('h2,h3,h4,[class*="question"],[class*="faq-q"]');var a=it.querySelector('[class*="answer"],[class*="faq-a"],p');if(q&&a){var qt=q.textContent.trim(),at=a.textContent.trim();if(qt&&at&&qt.length<300)items.push({"@type":"Question","name":qt,"acceptedAnswer":{"@type":"Answer","text":at}})}});if(items.length){var fj=document.createElement('script');fj.type='application/ld+json';fj.setAttribute('data-cwdb-faq','1');fj.textContent=JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":items});document.head.appendChild(fj)}}}
}catch(e){console.warn('[cwdb-r3]',e)}})})();
